version: '3.8'
services:
  app:
    build: .
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file watching
      - WATCHPACK_POLLING=true    # Enable polling for Vite/Webpack
    command: npm run dev -- --host

    # the --host is needed cos i'm using vite
    # vite requires it to connect to external ports outside the local machine
    # which in this case is docker

    # command: npm run dev

    # I will use this in production
    # command: npm run preview